spring:
  datasource:
    url: jdbc:mysql://db.yeoyck.com:3306/varie
    username: kin
    password: 986527@Yck
  hikari:
    catalog: varie
    schema: varie
  jpa:
    properties:
      dialect: com.varie.dao.sql.custom.CustomMySqlDialect
      show_sql: true
      format_sql: false
general:
  ui:
    url: http://localhost:3080
